[package]
name = "otpgen"
version = "0.1.1"
edition = "2021"
description = "One-time pad generator"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
termprogress = "0.3.4"
