[package]
name = "otpgen"
version = "0.1.1"
edition = "2021"
description = "One-time pad generator"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
ansi_term = "0.9.0"
