[package]
name = "otpgen"
version = "0.2.0"
edition = "2021"
description = "Generates cryptographic one-time pads."
license = "GPL-3.0-only"

[dependencies]
rand = "0.7.3"
termprogress = "0.3.4"
clap = "~2.33.0"
